# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWidget(object):
    def setupUi(self, MainWidget):
        MainWidget.setObjectName(_fromUtf8("MainWidget"))
        MainWidget.resize(541, 377)
        MainWidget.setMinimumSize(QtCore.QSize(0, 0))
        MainWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gridLayout_5 = QtGui.QGridLayout(MainWidget)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox = QtGui.QGroupBox(MainWidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.soller_x_down_btn = QtGui.QPushButton(self.groupBox)
        self.soller_x_down_btn.setMaximumSize(QtCore.QSize(20, 16777215))
        self.soller_x_down_btn.setObjectName(_fromUtf8("soller_x_down_btn"))
        self.gridLayout.addWidget(self.soller_x_down_btn, 0, 2, 1, 1)
        self.soller_x_step_txt = QtGui.QLineEdit(self.groupBox)
        self.soller_x_step_txt.setMaximumSize(QtCore.QSize(50, 16777215))
        self.soller_x_step_txt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.soller_x_step_txt.setObjectName(_fromUtf8("soller_x_step_txt"))
        self.gridLayout.addWidget(self.soller_x_step_txt, 0, 3, 1, 1)
        self.soller_x_pos_txt = QtGui.QLineEdit(self.groupBox)
        self.soller_x_pos_txt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.soller_x_pos_txt.setObjectName(_fromUtf8("soller_x_pos_txt"))
        self.gridLayout.addWidget(self.soller_x_pos_txt, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.soller_z_up_btn = QtGui.QPushButton(self.groupBox)
        self.soller_z_up_btn.setMaximumSize(QtCore.QSize(20, 16777215))
        self.soller_z_up_btn.setObjectName(_fromUtf8("soller_z_up_btn"))
        self.gridLayout.addWidget(self.soller_z_up_btn, 1, 4, 1, 1)
        self.soller_z_down_btn = QtGui.QPushButton(self.groupBox)
        self.soller_z_down_btn.setMaximumSize(QtCore.QSize(20, 16777215))
        self.soller_z_down_btn.setObjectName(_fromUtf8("soller_z_down_btn"))
        self.gridLayout.addWidget(self.soller_z_down_btn, 1, 2, 1, 1)
        self.soller_z_step_txt = QtGui.QLineEdit(self.groupBox)
        self.soller_z_step_txt.setMaximumSize(QtCore.QSize(50, 16777215))
        self.soller_z_step_txt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.soller_z_step_txt.setObjectName(_fromUtf8("soller_z_step_txt"))
        self.gridLayout.addWidget(self.soller_z_step_txt, 1, 3, 1, 1)
        self.soller_z_pos_txt = QtGui.QLineEdit(self.groupBox)
        self.soller_z_pos_txt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.soller_z_pos_txt.setObjectName(_fromUtf8("soller_z_pos_txt"))
        self.gridLayout.addWidget(self.soller_z_pos_txt, 1, 1, 1, 1)
        self.soller_x_up_btn = QtGui.QPushButton(self.groupBox)
        self.soller_x_up_btn.setMaximumSize(QtCore.QSize(20, 16777215))
        self.soller_x_up_btn.setObjectName(_fromUtf8("soller_x_up_btn"))
        self.gridLayout.addWidget(self.soller_x_up_btn, 0, 4, 1, 1)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_3 = QtGui.QGroupBox(MainWidget)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_9 = QtGui.QLabel(self.groupBox_3)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_3.addWidget(self.label_9, 0, 0, 1, 1)
        self.center_offset_txt = QtGui.QLineEdit(self.groupBox_3)
        self.center_offset_txt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.center_offset_txt.setObjectName(_fromUtf8("center_offset_txt"))
        self.gridLayout_3.addWidget(self.center_offset_txt, 0, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox_3)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_3.addWidget(self.label_10, 1, 0, 1, 1)
        self.theta_offset_txt = QtGui.QLineEdit(self.groupBox_3)
        self.theta_offset_txt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.theta_offset_txt.setObjectName(_fromUtf8("theta_offset_txt"))
        self.gridLayout_3.addWidget(self.theta_offset_txt, 1, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_3)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 2, 0, 1, 1)
        self.soller_theta_pos_txt = QtGui.QLineEdit(self.groupBox_3)
        self.soller_theta_pos_txt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.soller_theta_pos_txt.setObjectName(_fromUtf8("soller_theta_pos_txt"))
        self.gridLayout_3.addWidget(self.soller_theta_pos_txt, 2, 1, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.soller_theta_down_btn = QtGui.QPushButton(self.groupBox_3)
        self.soller_theta_down_btn.setMaximumSize(QtCore.QSize(20, 16777215))
        self.soller_theta_down_btn.setObjectName(_fromUtf8("soller_theta_down_btn"))
        self.horizontalLayout.addWidget(self.soller_theta_down_btn)
        self.soller_theta_step_txt = QtGui.QLineEdit(self.groupBox_3)
        self.soller_theta_step_txt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.soller_theta_step_txt.setObjectName(_fromUtf8("soller_theta_step_txt"))
        self.horizontalLayout.addWidget(self.soller_theta_step_txt)
        self.soller_theta_up_btn = QtGui.QPushButton(self.groupBox_3)
        self.soller_theta_up_btn.setMaximumSize(QtCore.QSize(20, 16777215))
        self.soller_theta_up_btn.setObjectName(_fromUtf8("soller_theta_up_btn"))
        self.horizontalLayout.addWidget(self.soller_theta_up_btn)
        self.gridLayout_3.addLayout(self.horizontalLayout, 3, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.gridLayout_5.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.status_txt = QtGui.QLabel(MainWidget)
        self.status_txt.setStyleSheet(_fromUtf8("font-size: 20px; color: red;"))
        self.status_txt.setText(_fromUtf8(""))
        self.status_txt.setAlignment(QtCore.Qt.AlignCenter)
        self.status_txt.setObjectName(_fromUtf8("status_txt"))
        self.verticalLayout.addWidget(self.status_txt)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.groupBox_2 = QtGui.QGroupBox(MainWidget)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.collection_time_txt = QtGui.QLineEdit(self.groupBox_2)
        self.collection_time_txt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.collection_time_txt.setObjectName(_fromUtf8("collection_time_txt"))
        self.gridLayout_2.addWidget(self.collection_time_txt, 1, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 1, 2, 1, 1)
        self.detector_pv_txt = QtGui.QLineEdit(self.groupBox_2)
        self.detector_pv_txt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.detector_pv_txt.setObjectName(_fromUtf8("detector_pv_txt"))
        self.gridLayout_2.addWidget(self.detector_pv_txt, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.collect_btn = QtGui.QPushButton(self.groupBox_2)
        self.collect_btn.setMinimumSize(QtCore.QSize(0, 50))
        self.collect_btn.setObjectName(_fromUtf8("collect_btn"))
        self.gridLayout_2.addWidget(self.collect_btn, 4, 1, 1, 2)
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.collection_angle_txt = QtGui.QLineEdit(self.groupBox_2)
        self.collection_angle_txt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.collection_angle_txt.setObjectName(_fromUtf8("collection_angle_txt"))
        self.gridLayout_2.addWidget(self.collection_angle_txt, 2, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 2, 2, 1, 1)
        self.start_angle_txt = QtGui.QLineEdit(self.groupBox_2)
        self.start_angle_txt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.start_angle_txt.setObjectName(_fromUtf8("start_angle_txt"))
        self.gridLayout_2.addWidget(self.start_angle_txt, 3, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.groupBox_2)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_2.addWidget(self.label_12, 3, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.gridLayout_5.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(MainWidget)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.pv2_min_txt = QtGui.QLineEdit(self.groupBox_4)
        self.pv2_min_txt.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pv2_min_txt.sizePolicy().hasHeightForWidth())
        self.pv2_min_txt.setSizePolicy(sizePolicy)
        self.pv2_min_txt.setMaximumSize(QtCore.QSize(65, 16777215))
        self.pv2_min_txt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pv2_min_txt.setObjectName(_fromUtf8("pv2_min_txt"))
        self.gridLayout_4.addWidget(self.pv2_min_txt, 2, 2, 1, 1)
        self.pv1_min_txt = QtGui.QLineEdit(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pv1_min_txt.sizePolicy().hasHeightForWidth())
        self.pv1_min_txt.setSizePolicy(sizePolicy)
        self.pv1_min_txt.setMaximumSize(QtCore.QSize(65, 16777215))
        self.pv1_min_txt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pv1_min_txt.setObjectName(_fromUtf8("pv1_min_txt"))
        self.gridLayout_4.addWidget(self.pv1_min_txt, 1, 2, 1, 1)
        self.label_16 = QtGui.QLabel(self.groupBox_4)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_4.addWidget(self.label_16, 3, 3, 1, 1)
        self.label_15 = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_4.addWidget(self.label_15, 0, 3, 1, 1)
        self.label_18 = QtGui.QLabel(self.groupBox_4)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_4.addWidget(self.label_18, 3, 5, 1, 1)
        self.label_14 = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_4.addWidget(self.label_14, 0, 2, 1, 1)
        self.pv2_max_txt = QtGui.QLineEdit(self.groupBox_4)
        self.pv2_max_txt.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pv2_max_txt.sizePolicy().hasHeightForWidth())
        self.pv2_max_txt.setSizePolicy(sizePolicy)
        self.pv2_max_txt.setMaximumSize(QtCore.QSize(65, 16777215))
        self.pv2_max_txt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pv2_max_txt.setObjectName(_fromUtf8("pv2_max_txt"))
        self.gridLayout_4.addWidget(self.pv2_max_txt, 2, 3, 1, 1)
        self.pv1_step_txt = QtGui.QLineEdit(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pv1_step_txt.sizePolicy().hasHeightForWidth())
        self.pv1_step_txt.setSizePolicy(sizePolicy)
        self.pv1_step_txt.setMaximumSize(QtCore.QSize(65, 16777215))
        self.pv1_step_txt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pv1_step_txt.setObjectName(_fromUtf8("pv1_step_txt"))
        self.gridLayout_4.addWidget(self.pv1_step_txt, 1, 4, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBox_4)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_4.addWidget(self.label_11, 0, 1, 1, 1)
        self.pv1_name_txt = QtGui.QLineEdit(self.groupBox_4)
        self.pv1_name_txt.setObjectName(_fromUtf8("pv1_name_txt"))
        self.gridLayout_4.addWidget(self.pv1_name_txt, 1, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_4.addWidget(self.label_13, 0, 4, 1, 1)
        self.pv2_step_txt = QtGui.QLineEdit(self.groupBox_4)
        self.pv2_step_txt.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pv2_step_txt.sizePolicy().hasHeightForWidth())
        self.pv2_step_txt.setSizePolicy(sizePolicy)
        self.pv2_step_txt.setMaximumSize(QtCore.QSize(65, 16777215))
        self.pv2_step_txt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pv2_step_txt.setObjectName(_fromUtf8("pv2_step_txt"))
        self.gridLayout_4.addWidget(self.pv2_step_txt, 2, 4, 1, 1)
        self.map_sleep_txt = QtGui.QLineEdit(self.groupBox_4)
        self.map_sleep_txt.setMinimumSize(QtCore.QSize(50, 0))
        self.map_sleep_txt.setMaximumSize(QtCore.QSize(65, 16777215))
        self.map_sleep_txt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.map_sleep_txt.setObjectName(_fromUtf8("map_sleep_txt"))
        self.gridLayout_4.addWidget(self.map_sleep_txt, 3, 4, 1, 1)
        self.pv1_max_txt = QtGui.QLineEdit(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pv1_max_txt.sizePolicy().hasHeightForWidth())
        self.pv1_max_txt.setSizePolicy(sizePolicy)
        self.pv1_max_txt.setMaximumSize(QtCore.QSize(65, 16777215))
        self.pv1_max_txt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pv1_max_txt.setObjectName(_fromUtf8("pv1_max_txt"))
        self.gridLayout_4.addWidget(self.pv1_max_txt, 1, 3, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem1, 0, 7, 1, 1)
        self.pv2_name_txt = QtGui.QLineEdit(self.groupBox_4)
        self.pv2_name_txt.setEnabled(False)
        self.pv2_name_txt.setObjectName(_fromUtf8("pv2_name_txt"))
        self.gridLayout_4.addWidget(self.pv2_name_txt, 2, 1, 1, 1)
        self.collect_map_btn = QtGui.QPushButton(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.collect_map_btn.sizePolicy().hasHeightForWidth())
        self.collect_map_btn.setSizePolicy(sizePolicy)
        self.collect_map_btn.setObjectName(_fromUtf8("collect_map_btn"))
        self.gridLayout_4.addWidget(self.collect_map_btn, 1, 7, 3, 1)
        self.pv1_cur_lbl = QtGui.QLabel(self.groupBox_4)
        self.pv1_cur_lbl.setObjectName(_fromUtf8("pv1_cur_lbl"))
        self.gridLayout_4.addWidget(self.pv1_cur_lbl, 1, 5, 1, 1)
        self.pv2_cb = QtGui.QCheckBox(self.groupBox_4)
        self.pv2_cb.setText(_fromUtf8(""))
        self.pv2_cb.setChecked(False)
        self.pv2_cb.setObjectName(_fromUtf8("pv2_cb"))
        self.gridLayout_4.addWidget(self.pv2_cb, 2, 0, 1, 1)
        self.pv2_cur_lbl = QtGui.QLabel(self.groupBox_4)
        self.pv2_cur_lbl.setObjectName(_fromUtf8("pv2_cur_lbl"))
        self.gridLayout_4.addWidget(self.pv2_cur_lbl, 2, 5, 1, 1)
        self.pv1_num_lbl = QtGui.QLabel(self.groupBox_4)
        self.pv1_num_lbl.setObjectName(_fromUtf8("pv1_num_lbl"))
        self.gridLayout_4.addWidget(self.pv1_num_lbl, 1, 6, 1, 1)
        self.pv2_num_lbl = QtGui.QLabel(self.groupBox_4)
        self.pv2_num_lbl.setObjectName(_fromUtf8("pv2_num_lbl"))
        self.gridLayout_4.addWidget(self.pv2_num_lbl, 2, 6, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_4, 1, 0, 1, 2)

        self.retranslateUi(MainWidget)
        QtCore.QMetaObject.connectSlotsByName(MainWidget)

    def retranslateUi(self, MainWidget):
        MainWidget.setWindowTitle(_translate("MainWidget", "Form", None))
        self.groupBox.setTitle(_translate("MainWidget", "Soller Slit Position", None))
        self.soller_x_down_btn.setText(_translate("MainWidget", "<", None))
        self.soller_x_step_txt.setText(_translate("MainWidget", "0.01", None))
        self.soller_x_pos_txt.setText(_translate("MainWidget", "0.000", None))
        self.label_2.setText(_translate("MainWidget", "Soller Z:", None))
        self.soller_z_up_btn.setText(_translate("MainWidget", ">", None))
        self.soller_z_down_btn.setText(_translate("MainWidget", "<", None))
        self.soller_z_step_txt.setText(_translate("MainWidget", "0.01", None))
        self.soller_z_pos_txt.setText(_translate("MainWidget", "0.000", None))
        self.soller_x_up_btn.setText(_translate("MainWidget", ">", None))
        self.label.setText(_translate("MainWidget", "Soller X:", None))
        self.groupBox_3.setTitle(_translate("MainWidget", "Rotation", None))
        self.label_9.setText(_translate("MainWidget", "Center Offset:", None))
        self.label_10.setText(_translate("MainWidget", "Theta Offset:", None))
        self.label_8.setText(_translate("MainWidget", "Soller Theta:", None))
        self.soller_theta_down_btn.setText(_translate("MainWidget", "<", None))
        self.soller_theta_step_txt.setText(_translate("MainWidget", "5", None))
        self.soller_theta_up_btn.setText(_translate("MainWidget", ">", None))
        self.groupBox_2.setTitle(_translate("MainWidget", "Data Collection", None))
        self.label_5.setText(_translate("MainWidget", "s", None))
        self.label_4.setText(_translate("MainWidget", "Collection time:", None))
        self.collect_btn.setText(_translate("MainWidget", "Collect", None))
        self.label_3.setText(_translate("MainWidget", "Detector PV:", None))
        self.label_6.setText(_translate("MainWidget", "Angle:", None))
        self.label_7.setText(_translate("MainWidget", "°", None))
        self.label_12.setText(_translate("MainWidget", "Start Angle:", None))
        self.groupBox_4.setTitle(_translate("MainWidget", "Mapping", None))
        self.pv2_min_txt.setText(_translate("MainWidget", "-0.01", None))
        self.pv1_min_txt.setText(_translate("MainWidget", "-0.01", None))
        self.label_16.setText(_translate("MainWidget", "Sleep:", None))
        self.label_15.setText(_translate("MainWidget", "max", None))
        self.label_18.setText(_translate("MainWidget", "s", None))
        self.label_14.setText(_translate("MainWidget", "min", None))
        self.pv2_max_txt.setText(_translate("MainWidget", "0.01", None))
        self.pv1_step_txt.setText(_translate("MainWidget", "0.005", None))
        self.label_11.setText(_translate("MainWidget", "PV name", None))
        self.label_13.setText(_translate("MainWidget", "step", None))
        self.pv2_step_txt.setText(_translate("MainWidget", "0.005", None))
        self.map_sleep_txt.setToolTip(_translate("MainWidget", "<html><head/><body><p>Time to wait between each collection (especially useful for MarIP).</p></body></html>", None))
        self.map_sleep_txt.setText(_translate("MainWidget", "0", None))
        self.pv1_max_txt.setText(_translate("MainWidget", "0.01", None))
        self.collect_map_btn.setText(_translate("MainWidget", "Collect Map", None))
        self.pv1_cur_lbl.setText(_translate("MainWidget", "0", None))
        self.pv2_cur_lbl.setText(_translate("MainWidget", "0", None))
        self.pv1_num_lbl.setText(_translate("MainWidget", "0", None))
        self.pv2_num_lbl.setText(_translate("MainWidget", "0", None))

