# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main.ui'
#
# Created: Fri Oct 03 17:49:56 2014
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWidget(object):
    def setupUi(self, MainWidget):
        MainWidget.setObjectName(_fromUtf8("MainWidget"))
        MainWidget.resize(500, 250)
        MainWidget.setMinimumSize(QtCore.QSize(500, 250))
        MainWidget.setMaximumSize(QtCore.QSize(500, 250))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(MainWidget)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox = QtGui.QGroupBox(MainWidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.soller_x_down_btn = QtGui.QPushButton(self.groupBox)
        self.soller_x_down_btn.setMaximumSize(QtCore.QSize(20, 16777215))
        self.soller_x_down_btn.setObjectName(_fromUtf8("soller_x_down_btn"))
        self.gridLayout.addWidget(self.soller_x_down_btn, 0, 2, 1, 1)
        self.soller_x_step_txt = QtGui.QLineEdit(self.groupBox)
        self.soller_x_step_txt.setMaximumSize(QtCore.QSize(50, 16777215))
        self.soller_x_step_txt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.soller_x_step_txt.setObjectName(_fromUtf8("soller_x_step_txt"))
        self.gridLayout.addWidget(self.soller_x_step_txt, 0, 3, 1, 1)
        self.soller_x_pos_txt = QtGui.QLineEdit(self.groupBox)
        self.soller_x_pos_txt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.soller_x_pos_txt.setObjectName(_fromUtf8("soller_x_pos_txt"))
        self.gridLayout.addWidget(self.soller_x_pos_txt, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.soller_z_up_btn = QtGui.QPushButton(self.groupBox)
        self.soller_z_up_btn.setMaximumSize(QtCore.QSize(20, 16777215))
        self.soller_z_up_btn.setObjectName(_fromUtf8("soller_z_up_btn"))
        self.gridLayout.addWidget(self.soller_z_up_btn, 1, 4, 1, 1)
        self.soller_z_down_btn = QtGui.QPushButton(self.groupBox)
        self.soller_z_down_btn.setMaximumSize(QtCore.QSize(20, 16777215))
        self.soller_z_down_btn.setObjectName(_fromUtf8("soller_z_down_btn"))
        self.gridLayout.addWidget(self.soller_z_down_btn, 1, 2, 1, 1)
        self.soller_z_step_txt = QtGui.QLineEdit(self.groupBox)
        self.soller_z_step_txt.setMaximumSize(QtCore.QSize(50, 16777215))
        self.soller_z_step_txt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.soller_z_step_txt.setObjectName(_fromUtf8("soller_z_step_txt"))
        self.gridLayout.addWidget(self.soller_z_step_txt, 1, 3, 1, 1)
        self.soller_z_pos_txt = QtGui.QLineEdit(self.groupBox)
        self.soller_z_pos_txt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.soller_z_pos_txt.setObjectName(_fromUtf8("soller_z_pos_txt"))
        self.gridLayout.addWidget(self.soller_z_pos_txt, 1, 1, 1, 1)
        self.soller_x_up_btn = QtGui.QPushButton(self.groupBox)
        self.soller_x_up_btn.setMaximumSize(QtCore.QSize(20, 16777215))
        self.soller_x_up_btn.setObjectName(_fromUtf8("soller_x_up_btn"))
        self.gridLayout.addWidget(self.soller_x_up_btn, 0, 4, 1, 1)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_3 = QtGui.QGroupBox(MainWidget)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_9 = QtGui.QLabel(self.groupBox_3)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_3.addWidget(self.label_9, 0, 0, 1, 1)
        self.center_offset_txt = QtGui.QLineEdit(self.groupBox_3)
        self.center_offset_txt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.center_offset_txt.setObjectName(_fromUtf8("center_offset_txt"))
        self.gridLayout_3.addWidget(self.center_offset_txt, 0, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox_3)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_3.addWidget(self.label_10, 1, 0, 1, 1)
        self.theta_offset_txt = QtGui.QLineEdit(self.groupBox_3)
        self.theta_offset_txt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.theta_offset_txt.setObjectName(_fromUtf8("theta_offset_txt"))
        self.gridLayout_3.addWidget(self.theta_offset_txt, 1, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_3)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 2, 0, 1, 1)
        self.soller_theta_pos_txt = QtGui.QLineEdit(self.groupBox_3)
        self.soller_theta_pos_txt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.soller_theta_pos_txt.setObjectName(_fromUtf8("soller_theta_pos_txt"))
        self.gridLayout_3.addWidget(self.soller_theta_pos_txt, 2, 1, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.soller_theta_down_btn = QtGui.QPushButton(self.groupBox_3)
        self.soller_theta_down_btn.setMaximumSize(QtCore.QSize(20, 16777215))
        self.soller_theta_down_btn.setObjectName(_fromUtf8("soller_theta_down_btn"))
        self.horizontalLayout.addWidget(self.soller_theta_down_btn)
        self.soller_theta_step_txt = QtGui.QLineEdit(self.groupBox_3)
        self.soller_theta_step_txt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.soller_theta_step_txt.setObjectName(_fromUtf8("soller_theta_step_txt"))
        self.horizontalLayout.addWidget(self.soller_theta_step_txt)
        self.soller_theta_up_btn = QtGui.QPushButton(self.groupBox_3)
        self.soller_theta_up_btn.setMaximumSize(QtCore.QSize(20, 16777215))
        self.soller_theta_up_btn.setObjectName(_fromUtf8("soller_theta_up_btn"))
        self.horizontalLayout.addWidget(self.soller_theta_up_btn)
        self.gridLayout_3.addLayout(self.horizontalLayout, 3, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.status_txt = QtGui.QLabel(MainWidget)
        self.status_txt.setStyleSheet(_fromUtf8("font-size: 20px; color: red;"))
        self.status_txt.setText(_fromUtf8(""))
        self.status_txt.setAlignment(QtCore.Qt.AlignCenter)
        self.status_txt.setObjectName(_fromUtf8("status_txt"))
        self.verticalLayout.addWidget(self.status_txt)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.groupBox_2 = QtGui.QGroupBox(MainWidget)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.collection_time_txt = QtGui.QLineEdit(self.groupBox_2)
        self.collection_time_txt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.collection_time_txt.setObjectName(_fromUtf8("collection_time_txt"))
        self.gridLayout_2.addWidget(self.collection_time_txt, 1, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 1, 2, 1, 1)
        self.detector_pv_txt = QtGui.QLineEdit(self.groupBox_2)
        self.detector_pv_txt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.detector_pv_txt.setObjectName(_fromUtf8("detector_pv_txt"))
        self.gridLayout_2.addWidget(self.detector_pv_txt, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.collect_btn = QtGui.QPushButton(self.groupBox_2)
        self.collect_btn.setMinimumSize(QtCore.QSize(0, 50))
        self.collect_btn.setObjectName(_fromUtf8("collect_btn"))
        self.gridLayout_2.addWidget(self.collect_btn, 3, 1, 1, 2)
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.collection_angle_txt = QtGui.QLineEdit(self.groupBox_2)
        self.collection_angle_txt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.collection_angle_txt.setObjectName(_fromUtf8("collection_angle_txt"))
        self.gridLayout_2.addWidget(self.collection_angle_txt, 2, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 2, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 23)

        self.retranslateUi(MainWidget)
        QtCore.QMetaObject.connectSlotsByName(MainWidget)

    def retranslateUi(self, MainWidget):
        MainWidget.setWindowTitle(_translate("MainWidget", "Form", None))
        self.groupBox.setTitle(_translate("MainWidget", "Soller Slit Position", None))
        self.soller_x_down_btn.setText(_translate("MainWidget", "<", None))
        self.soller_x_step_txt.setText(_translate("MainWidget", "0.01", None))
        self.soller_x_pos_txt.setText(_translate("MainWidget", "0.000", None))
        self.label_2.setText(_translate("MainWidget", "Soller Z:", None))
        self.soller_z_up_btn.setText(_translate("MainWidget", ">", None))
        self.soller_z_down_btn.setText(_translate("MainWidget", "<", None))
        self.soller_z_step_txt.setText(_translate("MainWidget", "0.01", None))
        self.soller_z_pos_txt.setText(_translate("MainWidget", "0.000", None))
        self.soller_x_up_btn.setText(_translate("MainWidget", ">", None))
        self.label.setText(_translate("MainWidget", "Soller X:", None))
        self.groupBox_3.setTitle(_translate("MainWidget", "Rotation", None))
        self.label_9.setText(_translate("MainWidget", "Center Offset:", None))
        self.label_10.setText(_translate("MainWidget", "Theta Offset:", None))
        self.label_8.setText(_translate("MainWidget", "Soller Theta:", None))
        self.soller_theta_down_btn.setText(_translate("MainWidget", "<", None))
        self.soller_theta_step_txt.setText(_translate("MainWidget", "5", None))
        self.soller_theta_up_btn.setText(_translate("MainWidget", ">", None))
        self.groupBox_2.setTitle(_translate("MainWidget", "Data Collection", None))
        self.label_5.setText(_translate("MainWidget", "s", None))
        self.label_4.setText(_translate("MainWidget", "Collection time:", None))
        self.collect_btn.setText(_translate("MainWidget", "Collect", None))
        self.label_3.setText(_translate("MainWidget", "Detector PV:", None))
        self.label_6.setText(_translate("MainWidget", "Angle:", None))
        self.label_7.setText(_translate("MainWidget", "°", None))

